---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml
  
  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir}}/config.yml"
      tags: ['always']
  
  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
  
  tasks:
    - include_tasks: tasks/fzf.yml
      when: install_fzf_utils